version: '0.1.{build}'

cache:
  - '%USERPROFILE%\.nuget\packages'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

os: Visual Studio 2019

init:
  - ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
  - choco install opencover.portable
  - choco install codecov

platform: Any CPU

configuration:
  - Debug

before_build:
  - dotnet restore
  - nuget restore

build:
  parallel: true
  project: GenericRange.sln
  verbosity: minimal

test_script:
  - dotnet test "tests/" --logger:"Appveyor" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - codecov -f "tests/coverage.opencover.xml"

artifacts:
  - path: tests\coverage*.xml
